name: Thomas Truongchau
description: Personal site of Thomas Truongchau
meta_description: "tommy's thoughts, stories, and ideas"

aboutPage: true

markdown: kramdown
highlighter: rouge

# paginate: 20
baseurl: /
domain_name: 'http://thomastruongchau.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'whysly'

# Details for the RSS feed generator
url:            'http://thomastruongchau.com'
author:         'Thomas Truongchau'
authorTwitter:  'ttruongchau'

permalink:       /:categories/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

# Other Jekyll Plugins
gems: [jemoji] # jekyll-paginate